spring.application.name=Digital-Gold-Wallet

server.port=8085
spring.devtools.livereload.enabled=true

spring.datasource.url=jdbc:mysql://10.10.174.222:3306/digitalgoldwallet

spring.datasource.username=anant
spring.datasource.password=1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true